# -*- coding: utf-8 -*-
"""AI_Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oh6QzA5B5ISqqOmtmjZOTgSKNVoWXrOp
"""



"""LIST

# **LIST**
"""

!pip install numpy
#creating a list of 10 integers
numbers = [1,2,12,4,5,6,7,8,9,10]
print('Original List',numbers)
# sum,max,min
print('Sum',sum(numbers))
print('Max',max(numbers))
print('Min',min(numbers))
#Adding number to the list
numbers.append(11)
#Removing number from the list
numbers.remove(5)
print('Updated List',numbers)
#Sort ascending and descending
print('Ascending',sorted(numbers))
print('Descending',sorted(numbers,reverse=True))

"""# **Tuples**"""

# creating a tuple with 5 strings
fruits = ('apple','banana','orange','grapes','mango')
print(fruits)
#printing the second last and last index
print('Second Element :',fruits[1])
print('Last Element :',fruits[-1])
#try to modify so give error or not
#fruits[1] = 'kiwi'

#now add element to tuple through converting it to list and than back to tuple
fruits = list(fruits)
fruits.append('kiwi')
fruits = tuple(fruits)
print(fruits)

"""# **Dictionary**"""

#creating 5 keys-values of studentnames and marks
student_marks = {
    'Alice': 85,
    'Bob': 92,
    'Charlie': 78,
    'David': 95,
    'Eve': 88
}

print(student_marks)
#print value and keys
print('Keys :',student_marks.keys())
print('Updated Dictionary',student_marks)

"""# **Numpy**

# **Sets**
"""

#creating two sets with some common and unique elements
set1 = {1,2,3,4,5}
set2 = {4,5,6,7,8}
#union
print('Union',set1.union(set2))
#intersection
print('Intersection',set1.intersection(set2))
#diffrences
print('Difference',set1 - set2)

"""# **Matplotlib**"""