# -*- coding: utf-8 -*-
"""ResultsReproduce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hMaMMXGl9IkBObz7Bzp7xRb0M9cbyxda
"""



"""# **Numpy**"""

import numpy as np
#Creator : Tahir Ahmad
# Create 1D array
arr = np.arange(3, 23)
print('1D Array:', arr)

# Reshape to 4x5 matrix
matrix = arr.reshape(4, 5)
print('4x5 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Element-wise operations
arr2 = np.arange(21, 41)
print('Addition:', arr + arr2)
print('Multiplication:', arr * arr2)

"""# **Matplotlib**"""

import matplotlib.pyplot as plt
#Author : Tahir Ahmad
# Line Plot
x = list(range(1, 11))
y = [i**2 for i in x]
plt.plot(x, y)
plt.title('Numbers vs Squares')
plt.xlabel('Numbers')
plt.ylabel('Squares')
plt.show()

# Bar Chart
students = ['Tahir', 'Mashal', 'Aryan', 'Zara', 'Omar']
marks = [85, 90, 78, 92, 88]
plt.bar(students, marks)
plt.title('Student Marks')
plt.xlabel('Students')
plt.ylabel('Marks')
plt.show()

# Pie Chart
categories = ['Category A', 'Category B', 'Category C']
values = [30, 50, 20]
plt.pie(values, labels=categories, autopct='%1.1f%%')
plt.title('Category Distribution')
plt.show()